// react-app/src/components/Login.jsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';

function Login() {
  const [email, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const navigate = useNavigate();

  const handleSubmit = async (e) => {
    e.preventDefault(); // Отменяет стандартное действие браузера, предотвращает перезагрузку страницы при отправке формы
    
    const app_id = 1;

    try {
      const response = await fetch('http://localhost:8080/auth/login', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({app_id: app_id, email, password}),
      });

      if (response.ok){
        const data = await response.json();

        if (data.accessToken && data.refreshToken){
          localStorage.setItem('access_token', data.accessToken);
          localStorage.setItem('refresh_token', data.refreshToken);
          localStorage.setItem('isAuthenticated', 'true');
          localStorage.setItem('app_id', app_id);
          localStorage.setItem('user_id', data.userId);

          const adminCheck = await fetch(`http://localhost:8080/auth/admin/${data.userId}`, {
          method: 'GET',
          headers: {
            'Content-Type': 'application/json',
                  },
          });

          const blockedCheck = await fetch(`http://localhost:8080/auth/block-status/${data.userId}`, {
            method: 'GET',
            headers: {
            'Content-Type': 'application/json',
                  },
          });

        if (adminCheck.ok && blockedCheck.ok){
          const adminData = await adminCheck.json();
          const blockedData = await blockedCheck.json();
          if (blockedData.isBlocked === false){
              if (adminData.isAdmin === true){
              localStorage.setItem('isAdmin', 'true');
            }else{
              localStorage.setItem('isAdmin', 'false');
            }
          }else {
            localStorage.clear();
            navigate('/register')
          }
        }
        navigate('/')

        }else{
          setError('Ошибка авторизации: недопустимые токены');
        }
      }else{
        setError('Неверный email или пароль');
      }
    }catch (error){
      setError('Ошибка при подключении к серверу');
      console.error(error);
    }
  };

  return (
    <div className="login">
      <h1>Вход</h1>
      {error && <p className="error">{error}</p>}
      <form onSubmit={handleSubmit}> 
        <div>
          <label>Имя пользователя:</label>
          <input
            type="text"
            value={email}
            onChange={(e) => setUsername(e.target.value)}
            required
          />
        </div>
        <div>
          <label>Пароль:</label>
          <input
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
          />
        </div>
        <button type="submit">Войти</button>
      </form>
    </div>
  );
}

export default Login;

// admin-panel/src/app/login/login.component.ts
// login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { forkJoin } from 'rxjs';
import { switchMap, map } from 'rxjs/operators';

@Component({
  selector: 'app-login',
  standalone: true,
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
  imports: [ReactiveFormsModule, CommonModule],
})
export class LoginComponent {
  loading = false;
  error: string | null = null;

  loginForm;

  private readonly APP_ID = 1;

  constructor(
    private fb: FormBuilder,
    private http: HttpClient,
    private router: Router
  ) {
    this.loginForm = this.fb.group({
      email: ['', Validators.required],
      password: ['', Validators.required],
    });
  }

  ngOnInit() {
    localStorage.clear(); 
  }

  login(): void {
    if (this.loginForm.invalid) return;

    this.loading = true;
    this.error = null;

    const { email, password } = this.loginForm.value as {
      email: string;
      password: string;
    };

    this.http
      .post<{
        accessToken: string;
        refreshToken: string;
        userId: number;
      }>('http://localhost:8080/auth/login', {
        app_id: this.APP_ID,
        email,
        password,
      })
      .pipe(
        switchMap((res) => {
          if (!res.accessToken || !res.refreshToken) {
            throw new Error('Недопустимые токены');
          }

          localStorage.setItem('access_token', res.accessToken);
          localStorage.setItem('refresh_token', res.refreshToken);
          localStorage.setItem('isAuthenticated', 'true');
          localStorage.setItem('app_id', String(this.APP_ID));
          localStorage.setItem('user_id', String(res.userId));

          const admin$ = this.http.get<{ isAdmin: boolean }>(
            `http://localhost:8080/auth/admin/${res.userId}`
          );
          const blocked$ = this.http.get<{ isBlocked: boolean }>(
            `http://localhost:8080/auth/block-status/${res.userId}`
          );

          return forkJoin([admin$, blocked$]).pipe(
            map(([adminData, blockedData]) => ({
              adminData,
              blockedData,
            }))
          );
        })
      )
      .subscribe({
        next: ({ adminData, blockedData }) => {
          this.loading = false;

          if (blockedData.isBlocked) {
            localStorage.clear();
            this.router.navigate(['/']);
            return;
          }

          if (!adminData.isAdmin) {
            // Если не админ — показываем ошибку и не сохраняем флаг
            this.error = 'Доступ запрещён: недостаточно прав';
            localStorage.clear();
            return;
          }

          // Если админ — сохраняем флаг и переходим дальше
          localStorage.setItem('isAdmin', 'true');
          this.router.navigate(['/']);
        },
        error: (err) => {
          this.loading = false;
          this.error =
            err?.message === 'Недопустимые токены'
              ? 'Ошибка авторизации: недопустимые токены'
              : err.status === 401 || err.status === 400
              ? 'Неверный email или пароль'
              : 'Ошибка при подключении к серверу';
        },
      });

  }
}

<div class="d-flex align-items-center justify-content-center">
  <div class="card p-4 bg-dark text-white" style="min-width:320px; max-width:400px; width:100%;">
    <h2 class="text-center mb-4">Вход</h2>
    <form [formGroup]="loginForm" (ngSubmit)="login()">
      <div class="mb-3">
        <input formControlName="email" class="form-control bg-secondary text-white border-0" placeholder="Логин" />
      </div>
      <div class="mb-3">
        <input type="password" formControlName="password" class="form-control bg-secondary text-white border-0" placeholder="Пароль" />
      </div>
      <div *ngIf="error" class="alert alert-danger py-2">{{ error }}</div>
      <button class="btn btn-success w-100" [disabled]="loading">Войти</button>
    </form>
  </div>
</div>
